web:
  command: sh -c "rails s --bind 0.0.0.0"
  ports:
    - "3000:3000"
  build: .
  volumes:
    - .:/app
  links:
    - redis:redis.local
    - mongodb:mongo.local
  environment:
    - REDIS_URL=redis://redis.local/0
    - MONGODB_HOST=mongo.local
    - CLIENT_ID=grupomining
    - CLIENT_SECRET=grupomining
    - SLAVES=githubproxy1.com,githubproxy2.com,githubproxy3.com

sidekiq:
  command: bundle exec sidekiq
  build: .
  volumes:
    - .:/app
  links:
    - redis:redis.local
    - mongodb:mongo.local
  environment:
    - REDIS_URL=redis://redis.local/0
    - MONGODB_HOST=mongo.local
    - CLIENT_ID=grupomining
    - CLIENT_SECRET=grupomining
    - SLAVES=githubproxy1.com,githubproxy2.com,githubproxy3.com

redis:
  image: redis:3.2

mongodb:
  image: mongo:3.3
